<?php

/**
 * Implements hook_ctools_plugin_directory().
*/
function aklinkitplugin_ctools_plugin_directory($module, $plugin) {
  if ($module == 'linkit' && !empty($plugin)) {
    return "plugins/" . $plugin;
  }
}

/**
 * Implements hook_menu().
*/
function aklinkitplugin_menu(){
    $items['aklinkitplugin/autocomplete'] = array(
    'page callback' => 'aklinkitplugin_autocomplete',
    'access callback' => 'reference_autocomplete_access',
    'access arguments' => array('node', 'book', 'field_authors'),
    'type' => MENU_CALLBACK,
  );
    $items['agreement-form'] = array(
	'title' => 'Upload agreement form',
	'description' => 'Upload the signed agreement.',
	'page callback' => 'ak_agreement_form',
	'access callback' => TRUE,
	'type' => MENU_NORMAL_ITEM,
    );
  return $items;
}

function ak_agreement_form() {
  global $user;
  $query = db_select('file_managed','f');
  $query->fields('f',array('fid'));
  $query->condition('f.type', 'agreement_scan' )
  ->condition('f.uid', $user->uid);
  $user_files = $query->execute()->fetchCol();
  if($user_files) {
  return '<h2>You have already submitted the agreement.</h2><p>In order to submit again contact administrator.</p>';
  } else {
  module_load_include('inc', 'file_entity', 'file_entity.pages');
  return drupal_get_form('file_entity_add_upload', array('file_directory' => 'agreements','file_extensions' => 'png jpeg jpg pdf'));
  }
}

/**
 * Implements hook_form_alter() 
 */
function aklinkitplugin_form_alter(&$form, &$form_state, $form_id){
    if($form_id == 'book_node_form'){   
	$max_delta = $form['field_authors']['und']['#max_delta'];
	for($i = 0; $i <= $max_delta ; $i++){
	$form['field_authors']['und'][$i]['nid']['#autocomplete_path'] = 'aklinkitplugin/autocomplete';
	}
    }
    if($form_id == 'file_entity_add_upload') {
	if($form['#step'] == 1) {
	  $form['#step'] += 1;
          $form_state['storage']['type'] = (current_path() == 'agreement-form') ? 'agreement_scan' : 'image';
	}
    }
}

/**
 * Page callback function
 * @param type $string
 * 
 */
function aklinkitplugin_autocomplete($string) {
    
  $query = db_select('node', 'n');
  $query->leftJoin('field_data_field_first_name', 'fn', 'n.nid = fn.entity_id');
  $query->addField('n', 'nid');
  $query->addField('n', 'title', 'node_title');
  $query->addField('fn', 'field_first_name_value', 'first_name');
  $query->condition('n.status', 1);
  $query->condition('n.type', 'person');
  
  $or = db_or();
  $or->condition('n.title', '%' . db_like($string) . '%', 'LIKE');
  $or->condition('fn.field_first_name_value', '%' . db_like($string) . '%', 'LIKE');
  $query->condition($or);
  
  $query->orderBy('n.nid','ASC');

  $result = $query->execute()->fetchAll();
  //var_dump($result);exit;
  $references = array();
  foreach ($result as $node) {
    $references[$node->nid] = array(
      'title'    => $node->node_title,
      'rendered' => check_plain( $node->node_title . ' ' . $node->first_name ),
    );
  }
  
  $matches = array();
  foreach ($references as $id => $row) {
    // Markup is fine in autocompletion results (might happen when rendered
    // through Views) but we want to remove hyperlinks.
    // remove following line - not using views
    //$suggestion = preg_replace('/<a href="([^<]*)">([^<]*)<\/a>/', '$2', $row['rendered']);
    // Add a class wrapper for a few required CSS overrides.
    
    //$matches[$row['title'] . " [nid:$id]"] = '<div class="reference-autocomplete">' . $suggestion . '</div>';
    $matches[$row['title'] . " [nid:$id]"] = '<div class="reference-autocomplete">' . $row['rendered'] . '</div>';
  }

  drupal_json_output($matches);
}